[[module.imports]]
path = "github.com/hbstack/base"

[[module.imports]]
path = "github.com/hbstack/carousel"

[[module.imports]]
path = "github.com/hbstack/socials"

[[module.imports]]
path = "github.com/hugomods/gravatar"

[[module.imports]]
path = "github.com/hugomods/icons/vendors/bootstrap"

[params.hb.blog]
paginate = 9
post_date_format = ':date_long'

[params.hb.blog.home]
# taxonomies_style = 'toggle'
