[[module.imports]]
path = "github.com/hbstack/blog"

[params.hugopress.modules.hb-blog-sidebar-taxonomies.hooks.hb-blog-sidebar]
cacheable = true

[params.hb.blog.sidebar.taxonomies]
count = true
limit = 10
separate = false
